# Generated by Django 2.2.3 on 2019-07-26 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_dishes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish', to='restaurant.Owner'),
        ),
    ]
